### ISSUE TITLE
Error on notices.pl prevents viewing of notices

### ISSUE THREAD

**Issue by kylemhall** [ldjamison/koha-plugin-room-reservations#14]
The javascript the plugin generates assumes the js var borrowernumber is defined on all pages it operates on. On notices.pl, this generates a javascript error as borrowernumber is not defined in js.

**Comment by edveal** [comment]
Thanks for reporting this Kyle.

**Comment by ldjamison** [comment]
Sheesh! Thanks for letting me know, @kylemhall ! I'll have a look at it! So far it's only erroring on notices.pl?

**Comment by edveal** [comment]
Is this needing testing?

**Comment by ldjamison** [comment]
@edveal I just merged @bartonski 's pull request. I'm going to close this issue but please test and open a new issue if you discover any problems during testing.

Thanks!
